# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(0, 0, 0, 50);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("QFrame{\n"
"    border-radius: 20px;\n"
"    background-color: rgb(255, 255, 255, 150);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("QFrame{\n"
"    image: url(:/img/icon/hias.png);\n"
"    background-color: rgb(47, 125, 238);\n"
"    border-radius: 20px;color: rgb(89, 217, 212);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("* {\n"
"  outline:none;\n"
"}\n"
"QListView{\n"
"  padding-top:24px;\n"
"  border-radius:20px;\n"
"  color:rgb(106,106,106);\n"
"\n"
"}\n"
"QListView::item{\n"
"  background-color:transparent;\n"
"  height:40px;\n"
"  padding-left:12px;\n"
"  padding:12px;\n"
"\n"
"}\n"
"QListView::item:hover{\n"
"  background-color:rgba(216,216,216,50);\n"
"\n"
"}\n"
"QListView::item:selected{\n"
"  background-color:rgba(90,216,212,50);\n"
"  color:rgb(40,92,90);\n"
"  border-left:2px solid rgb(90,216,212);\n"
"\n"
"}")
        self.listWidget.setIconSize(QtCore.QSize(24, 24))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/histogram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/average.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon2)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/maximum.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/rotating-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/flip-horizontally.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon5)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/flip-vertically.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon6)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/chart-histogram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon7)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icon/chart-line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon8)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icon/triangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon9)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icon/acoustic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon10)
        self.listWidget.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidget)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 6)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setStyleSheet("QFrame{\n"
"    background-color: rgb(0, 0, 0, 50);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.graphicsView = CustomGraphicsView(self.frame_5)
        self.graphicsView.setStyleSheet("QFrame{\n"
"    border-radius: 20px;\n"
"}")
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_3.addWidget(self.graphicsView)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255, 150);\n"
"    border-radius: 20px;\n"
"}\n"
"    \n"
"\n"
"\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget1 = QtWidgets.QListWidget(self.frame_4)
        self.listWidget1.setStyleSheet("* {\n"
"  outline:none;\n"
"}\n"
"QListView{\n"
"  border-radius:20px;\n"
"\n"
"}\n"
"QListView::item{\n"
"  background-color:transparent;\n"
"  padding-left:12px;\n"
"  padding:12px;\n"
"\n"
"}\n"
"QListView::item:hover{\n"
"  background-color:rgba(216,216,216,50);\n"
"\n"
"}\n"
"QListView::item:selected{\n"
"  background-color:rgba(90,216,212,50);\n"
"  color:rgb(40,92,90);\n"
"  border-left:2px solid rgb(90,216,212);\n"
"\n"
"}")
        self.listWidget1.setIconSize(QtCore.QSize(300, 300))
        self.listWidget1.setUniformItemSizes(True)
        self.listWidget1.setObjectName("listWidget1")
        self.verticalLayout.addWidget(self.listWidget1)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 5)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.listWidget.itemClicked['QListWidgetItem*'].connect(MainWindow.image_processing) # type: ignore
        self.listWidget1.itemClicked['QListWidgetItem*'].connect(MainWindow.image_display) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数字图像处理软件"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "直方图"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "直方图均衡化"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "自适应直方图均衡化"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "直方图规定化"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "旋转放缩"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "水平翻转"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "垂直翻转"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "空域平滑"))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "频域平滑"))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "锐化"))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "加噪"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
from CustomGraphicsView import CustomGraphicsView
import res_rc
